version: '3.8'

secrets:
  ycit021_mic2_fastapi_read_delete_secret002:
    external: true


networks:
  traefik-public:
    external: true

services:
  ycit021_mic2:
    image: ${DOCKER_LOGIN_USERNAME}/ycit021_prod_${SERVICE_NAME}:${PROJECT_VERSION}
    networks:
      - traefik-public
    secrets:
      - ycit021_mic2_fastapi_read_delete_secret002
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      placement:
        constraints:
          # - node.role == worker
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
    command:
      - /bin/bash
      - -c
      - |
        source /run/secrets/ycit021_mic2_fastapi_read_delete_secret002 && uvicorn main:app --host 0.0.0.0 --port 8080





