name="swarm-manager"
ami="ami-00842a994f5018db8"
instance_type="t2.small"
key_name="ycit021-master-key-1"
domain-name="codevteacher.com"
serverhostname="swarm-manager.codevteacher.com"
domain-owner-email="me@jasonjafari.com"