name: deploy
on:
  push:

jobs:
  deploy-services-in-swarm:
    name: Deploy services in swarm
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
      DOCKER_LOGIN_ACCESS_TOKEN: ${{ secrets.DOCKER_LOGIN_ACCESS_TOKEN }}


    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Deploy Infrastructure
        run: |
          ./iac.sh apply-all force
      - name: Copy sshkey
        run: |
          mkdir -p  ~/.ssh
          cp ./infrastructure/key-pairs/~~ycit021-master-key-6.pem ~/.ssh/swarm-manager
          chmod 400 ~/.ssh/swarm-manager
      - name: Add ssh configs
        run: |
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          echo "Host swarm-manager.public.codevteacher.com" >> ~/.ssh/config
          echo "  HostName swarm-manager.public.codevteacher.com" >> ~/.ssh/config
          echo "  User root" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/swarm-manager" >> ~/.ssh/config
          cat ~/.ssh/config;

      - name: test ssh
        run: |
          ssh root@swarm-manager.public.codevteacher.com "ls -la"

      - name: create a docker context my-swarm-manager
        run: |
          docker context create my-swarm-manager --docker "host=ssh://root@swarm-manager.public.codevteacher.com"
      - name: test docker context_name
        run: docker --context=my-swarm-manager ps -a