name: deploy
on:
  push:

jobs:
  deploy-services-in-swarm:
    name: Deploy services in swarm
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
      DOCKER_LOGIN_ACCESS_TOKEN: ${{ secrets.DOCKER_LOGIN_ACCESS_TOKEN }}


    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Deploy Infrastructure
        run: |
          ./iac.sh apply-all force
      - name: Set Environment Variables YCIT021_MASTER_KEY
        run: |
          cat ./infrastructure/key-pairs/~~ycit021-master-key-6.pem

          echo "YCIT021_MASTER_KEY=$(cat ./infrastructure/key-pairs/~~ycit021-master-key-6.pem)" >> $GITHUB_ENV
      - name: Install SSH key of swarm-manager
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.YCIT021_MASTER_KEY }}
          name: swarm-manager
          known_hosts: swarm-manager.public.codevteacher.com
          config: |
            StrictHostKeyChecking no
            Host swarm-manager.public.codevteacher.com
              HostName swarm-manager.public.codevteacher.com
              User root
              IdentityFile ~/.ssh/swarm-manager
      - name: test ssh
        run: |
          ssh root@swarm-manager.public.codevteacher.com "ls -la"